jobs:
  create_aks_cluster:
    intent: create
    resource: aks_cluster
    job_path: JobsFolder/Create-AKS-Cluster
    url: /job/JobsFolder/job/Create-AKS-Cluster/buildWithParameters
    documentation: https://learn.microsoft.com/azure/aks/
    parameters:
      - name: cluster_name
        prompt: Enter AKS Cluster Name
      - name: resource_group
        prompt: Enter Resource Group Name
      - name: location
        prompt: Enter Azure Location

  create_namespace:
    intent: create
    resource: namespace
    job_path: JobsFolder/Create-Namespace
    url: /job/JobsFolder/job/Create-Namespace/buildWithParameters
    documentation: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
    parameters:
      - name: cluster_name
        prompt: Enter Cluster Name
      - name: namespace
        prompt: Enter Namespace Name

  create_rolebinding:
    intent: create
    resource: rolebinding
    job_path: JobsFolder/Create-RoleBinding
    url: /job/JobsFolder/job/Create-RoleBinding/buildWithParameters
    documentation: https://kubernetes.io/docs/reference/access-authn-authz/rbac/
    parameters:
      - name: cluster_name
      - name: namespace
      - name: user
